@startuml Mayak

' Определение участников диаграммы
actor "Администратор" as Admin #Gray 
actor "Пользователь" as User #Red
actor "Благотворитель" as Donor #Green
participant "Платформа" as Platform #SkyBlue
participant "Сервис\n интеграции" as IntegrationService #GreenYellow
participant "Сервис рассылки\n UnisenderGo" as UnisenderGo #GreenYellow
participant "Сервис рассылки\n Unisender" as Unisender #GreenYellow
participant "Платёжный сервис\n CloudPayments" as CloudPayments #GreenYellow
participant "Платёжный сервис\n MixPlat" as MixPlat #GreenYellow

' Описание последовательности сообщений
User -> Platform: Выполнена регистрация на Платформе
== ФТ-001 ==
alt Регистрация успешна
    Platform -> IntegrationService: Регистрация на Платформе
        par 
        IntegrationService -> UnisenderGo: POST https://godocs.unisender.ru/web-api-ref#email-send
        UnisenderGo --> IntegrationService: Webhook
        IntegrationService -> UnisenderGo: POST https://godocs.unisender.ru/web-api-ref#email-validation-single
        UnisenderGo --> IntegrationService: Webhook
        end
    IntegrationService --> User: Сообщение с поздравляшками
else Регистрация не удалась
    Platform --> User: Ответ с ошибкой
end 

User -> Platform: Добавлено новое Событие
== ФТ-002 ==
Platform -> IntegrationService: Создано Событие
IntegrationService -> UnisenderGo: POST https://godocs.unisender.ru/web-api-ref#email-send 
UnisenderGo -> User: Ту-ту-ау, на Платформе создано новое Событие


@enduml