@startuml Donation

' Определение участников диаграммы
actor "Благотворитель" as Donor #Green
participant "1С-\nБитрикс" as Bitrix #RosyBrown
participant "Сервис\n интеграции" as IntService #SkyBlue
participant "Сервис рассылки\n UnisenderGo" as UnisenderGo #GreenYellow
participant "Сервис рассылки\n Unisender" as Unisender #GreenYellow
participant "Платёжный сервис\n CloudPayments" as CloudPayments #Orange

' Описание последовательности сообщений
Donor -> Bitrix: Заполнить форму оплаты пожертвований
activate Bitrix
Bitrix -> IntService: Запустить триггер оплаты\nPOST /donations/process
activate IntService
    opt Оплата с согласием на рассылку
        IntService -> Unisender: POST /email/subscribers\nPOST https://www.unisender.com/ru/support/api/messages/createemailmessage/
        Unisender --> IntService: Webhook\n 200 OK {email_id}
    end
IntService -> IntService: валидация email и дедупликация
IntService --> Bitrix: Сообщение о результатах валидации
deactivate Bitrix
IntService -> UnisenderGo: POST /email/send
activate UnisenderGo

alt email валиден и не дубликат
IntService -> CloudPayments: POST /payments
activate CloudPayments
    loop до 3 раз, если есть ошибка
        UnisenderGo --> IntService: 200 OK | 429/5xx error
        alt 200 OK
            IntService -> IntService: подождать
        else error и попытки не исчерпаны
            IntService -> IntService: подождать в 2 раза дольше
        else попытки исчерпаны
            IntService -> IntService: подождать в 4 раза дольше
        end
    CloudPayments --> IntService: Платёж прошёл
    UnisenderGo --> Donor: Письмо благодарности
    end
else email не прошёл проверку по RFC 5322
    CloudPayments --> IntService: Платёж не прошёл
    UnisenderGo --> Donor: Письмо о неудачном платеже (по ФТ-010)
    deactivate UnisenderGo
end

CloudPayments -> IntService: Ошибка платежа
deactivate CloudPayments
IntService -> Bitrix: Квитанция об ошибке
deactivate IntService

@enduml